#define LEDGER_CURRENCY_NTCR "NTCR"

#define LEDGER_CHANNEL_EVAC_DEPOSIT "EVAC_DEPOSIT"
#define LEDGER_CHANNEL_ROUND_CLOSE "ROUND_CLOSE"
#define LEDGER_CHANNEL_ADMIN_SEED "ADMIN_SEED"
#define LEDGER_CHANNEL_TITLE_PURCHASE "TITLE_PURCHASE"
#define LEDGER_CHANNEL_ATM_DEPOSIT "ATM_DEPOSIT"
#define LEDGER_CHANNEL_ATM_WITHDRAW "ATM_WITHDRAW"
#define LEDGER_CHANNEL_LOADOUT "LOADOUT"
#define LEDGER_CHANNEL_IDENTITY_MERGE "IDENTITY_MERGE"

#define LEDGER_STATUS_OK "ok"
#define LEDGER_STATUS_DUPLICATE "duplicate"
#define LEDGER_STATUS_INSUFFICIENT "insufficient"
#define LEDGER_STATUS_OFFLINE "offline"
#define LEDGER_STATUS_INVALID "invalid"
#define LEDGER_STATUS_FAILED "failed"
#define LEDGER_STATUS_NO_IDENTITY "no_identity"

#define ATM_DEPOSIT_LIMIT_DEFAULT 5000
#define ATM_WITHDRAW_LIMIT_DEFAULT 5000
#define EVAC_DEPOSIT_MULTIPLIER_DEFAULT 3
#define ATM_PIN_MIN 0
#define ATM_PIN_MAX 9999
